### ISSUE TITLE
Branching and versions

### ISSUE THREAD

**Issue by NathanDotTo** [CiscoDevNet/ydk-py#10]
Hi

Are there any plans to create versioned releases and branches for ydk-py? This would help us baseline our environment for reproducibility and automated testing purposes.

Many thanks

Nathan

**Comment by einarnn** [comment]
The ydk-py today does have a "version" associated with it, exposed via python packaging, which is currently 0.4.0.

But we are working on a couple of things in this area, yes. It would perhaps be helpful if you could outline what versioning your are thinking of. Model versioning, for example? Versioning of the YDK core libraries themselves? Or...?

Cheers,

Einar

**Comment by 111pontes** [comment]
YDK-Py releases are not tagged:
https://github.com/CiscoDevNet/ydk-py/releases
