### ISSUE TITLE
Read sample with pretty print

### ISSUE THREAD

**Issue by NathanDotTo** [CiscoDevNet/ydk-py#18]
Hi

Is here a sample of a read operation with something equivalent to a pretty print of the configuration that has been read?

Many thanks

Nathan

**Comment by abhikeshav** [comment]
If you'd like to examine what has been returned from a read operation in XML form, the [`codec_service.encode()`](http://ydk.cisco.com/py/docs/ydk.services.html#ydk.services.ydk.services.CodecService.encode) method may be useful

For example,

```
bgp_read = crud.read(provider, openconfig_bgp.Bgp())
codec_service = CodecService()
codec_provider = CodecServiceProvider(type='xml')

print codec_service.encode(codec_provider, bgp_read)
```

**Comment by 111pontes** [comment]
@NathanDotTo, see a full example at:
https://communities.cisco.com/message/232384 
In the future, please consider using the [YDK community](https://communities.cisco.com/community/developer/ydk) for general questions.  That approach benefits other users that may have similar questions. Thanks.

**Comment by NathanDotTo** [comment]
Many thanks.

Now I know about the community, I shall use it.

I can see the link for the community at the bottom of the README too, so I obviously did not read that far :-)

Regards

Nathan

> On 17 Oct 2016, at 18:55, Santiago Álvarez <notifications@github.com> wrote:
> 
> @NathanDotTo, see a full example at:
> https://communities.cisco.com/message/232384 
> In the future, please consider using the YDK community for general questions. That approach benefits other users that may have similar questions. Thanks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

—
Nathan John Sowatskey
Consulting Engineer - Programmable Infrastructure, DevOps, IoT and SDN
nathan@nathan.to
www.linkedin.com/in/nathandevops
XMPP: nathandotto@im.koderoot.net
Google: nathanjohnsowatskey@gmail.com
Skype: nathan_sowatskey
Twitter: NathanDotTo
GitHub: https://github.com/DevOps4Networks
http://www.kipling.org.uk/poems_if.htm
