### ISSUE TITLE
removing bgp asn with ydk-py

### ISSUE THREAD

**Issue by jedelman8** [CiscoDevNet/ydk-py#20]
Trying to remove a BGP ASN with ydk-py using a crud.delete() method and it's saying an instance is already created (error coming from XR device).

Any examples you can share for updating / deleting router-id and ASN ?

Thanks,
Jason

**Comment by 111pontes** [comment]
Two examples deleting BGP config:
1. XR native model: https://git.io/vXQjd
2. OC model: https://git.io/vX7em

**Comment by jedelman8** [comment]
Interesting, this is exactly what was tried yesterday and the device responded back with a message saying an inst was already configured.  

I suppose another question is, does a separate CRUDService instance need to be instantiated first?

```
crud = CRUDService()
crud.create(provider, bgp)
crud.delete(provider, bgp)
```

Should this work?

Or do we need to instantiate another object?

```
crud_c = CRUDService()
crud_c.create(provider, bgp)

crud = CRUDService()
crud.delete(provider, bgp)


```

I don't have access to my XR device now, but I'll try later too.

**Comment by 111pontes** [comment]
@jedelman8 , if you still are facing issues with your script, please let us know at https://communities.cisco.com/community/developer/ydk  I'll close this issue as this doesn't seem to be a YDK defect and those are tracked in the YDK-Gen repo any way.  Thanks.
