### ISSUE TITLE
API to return raw xml data 

### ISSUE THREAD

**Issue by madhusj13** [CiscoDevNet/ydk-py#23]
Can we have an API to get raw xml data, when I try to run ydk for getting oper data from the router ? 

There are multiple instances where xml output returned by the router is in-correct. Consequently, ydk returns 'YPYModelError: 0 already in list'. In such instances, it will be good to get the xml output in raw format.

**Comment by 111pontes** [comment]
Data validation is a feature.  One of the items being tracked is enhancing the error message so it's easier to identify the path to the erroneous data.  Regardless, you can use logging to inspect the raw XML. The samples apps in https://github.com/CiscoDevNet/ydk-py-samples make use of logging. In the future, please file issues in https://github.com/CiscoDevNet/ydk-gen  This repo is auto-generated.  Thanks.

**Comment by abhikeshav** [comment]
It may be a valid approach to include extra data (like invalid XML) in the python exception. see for example: http://legacy.python.org/dev/peps/pep-0473/. Maybe we should reopen this issue on the ydk-gen repo?
