### ISSUE TITLE
Potential misspell of attribute name

### ISSUE THREAD

**Issue by halochou** [CiscoDevNet/ydk-py#42]
https://github.com/CiscoDevNet/ydk-py/blob/db2feddee1d91c992fe1c6ac154133504b33d0fb/core/ydk/providers/_provider_plugin.py#L550

I experience an attribute access failure on this line.
After changing it to:
```
entity_ns = entity.i_meta.namespace
```
the failure resolved.

**Comment by ygorelik** [comment]
Fixed on [ydk-gen](https://github.com/CiscoDevNet/ydk-gen) branch 0.5.5.post2.
