### ISSUE TITLE
Installing ydk-py on Ubuntu 19.04 disco

### ISSUE THREAD

**Issue by mhdganji** [CiscoDevNet/ydk-py#49]
Hi, Python3 and Python3-pip installed successfully but when trying to install ydk-py using:

sudo -H pip3 install ydk-models-cisco-ios-xr

command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-l1f6352_/ydk/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-gwkg0f1j/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-l1f6352_/ydk/

**Comment by 111pontes** [comment]
This repo doesn't accept any issues directly. If you believe there is an issue in YDK that needs to be addressed, please open it in the CiscoDevNet/ydk-gen repo. Thanks.
