### ISSUE TITLE
OpenDaylightserviceprovider not working

### ISSUE THREAD

**Issue by benny007** [CiscoDevNet/ydk-py#51]
Hi,

I'm running ODL 0.11.1 and the docker image of YDK (0.8.4).

When I run the service provider query I got the following error:

`odl_provider = OpenDaylightServiceProvider(repo, "127.0.0.1", "admin", "admin", 8181, EncodingFormat.XML)`

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: type must be string, but is object
```

I noticed this happens only if my router is in connected state in my controller:

```

opendaylight-user@root>netconf:list-devices                                                                                                                                                                 
NETCONF ID          | NETCONF IP   | NETCONF Port | Status   
-------------------------------------------------------------
EDG-01-216.BRU1-IXN | 10.1.128.120 | 1830         | connected

```

When my router is in connecting state then the query succeeds without any issue

```
opendaylight-user@root>netconf:list-devices
NETCONF ID          | NETCONF IP   | NETCONF Port | Status    
--------------------------------------------------------------
EDG-01-216.BRU1-IXN | 10.1.128.120 | 1830         | connecting
```

I got the same result with ODL 0.8.3 and can't get it working.

The difference between connecting and connected state is the reply returned by ODL. In the first case it doesn't contains the capabilities of the router and the connected state the controller returns the full list of supported capabilities which (I think) leads to the above error.

Is this a bug ?

Thanks

**Comment by 111pontes** [comment]
This repo doesn't accept any issues directly. If you believe there is an issue in YDK that needs to be addressed, please open it in the CiscoDevNet/ydk-gen repo. Thanks.
